// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyupboplnowzfxnnqmup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dXBib3Bsbm93emZ4bm5xbXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTkwMjYsImV4cCI6MjA3MjQ5NTAyNn0.dKHfPJFFG9oHruhNO8zPholxLnUDngxippP8lxNh4Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});